### ISSUE TITLE
Add e2e tests for basic application 

### ISSUE THREAD

**Issue by chrislaughlin** [cam-technologies/time-booker#17]
Adding end to end tests for the current basic ember application.

**Comment by martinmicunda** [comment]
You can also use `protractor` for non angular project ... You just need to find how to write e2e test.

**Comment by chrislaughlin** [comment]
Here is an example of that tests for e2e
https://gist.github.com/chrislaughlin/cce12b3458e3030f32f8

**Comment by martinmicunda** [comment]
Yeah that's fine.. I would like to have at least some base e2e test to validate concat, minify etc are working correctly in production.

**Comment by chrislaughlin** [comment]
Okay Ill get the basic client one working first then look into the production ones

**Comment by chrislaughlin** [comment]
protractor seem to be very linked with Angular and I don't think it should be used by us as we are ember js. Im currently looking for an alternative.
