### ISSUE TITLE
Update Node and Gulp dependancies

### ISSUE THREAD

**Issue by chrislaughlin** [cam-technologies/time-booker#27]

**Comment by martinmicunda** [comment]
Just be carefull which dependencies you are updating.. I think the `gh-pages` and `karma` should not be updated as there are some issue with latest versions.

**Comment by chrislaughlin** [comment]
yeah I can see issues with karma, ill not update that.

**Comment by martinmicunda** [comment]
We should not update gulp-gh-pages plugins as the latest doesn't work. I have push pull request that we fix the build.

**Comment by chrislaughlin** [comment]
It passed the build

**Comment by martinmicunda** [comment]
yeah because for pull request we only run test and we are not publishing to gh-pages .. we are publishing for normal build when your merging pull request...

**Comment by chrislaughlin** [comment]
ah okay. Whats the process to run the full build locally so we can test changes like this.

**Comment by martinmicunda** [comment]
I don't think u need to run full build on your local env and even build script is customize for CI server. This is really small issue at should never happend till u don't update gulp-gh-pages (once they fix the issue in latest version we can update this plugin).
