### ISSUE TITLE
Find replacement for 'you-shall-not-commit' 

### ISSUE THREAD

**Issue by chrislaughlin** [cam-technologies/time-booker#43]
you shall not commit has become out of date with the most recent version of node, it has not had an update in 3 months and is currently on v 0.0.1

Going forward we need to look for an alternative as we currently can not update the version of node. 

Node v0.10.20 currently works with no issues.

**Comment by martinmicunda** [comment]
try this [pre-commit](https://www.npmjs.org/package/pre-commit) plugin

**Comment by chrislaughlin** [comment]
Just had a look myself, as long as they can run the gulp task then we are
sorted

On Thursday, July 10, 2014, Martin Micunda notifications@github.com wrote:

> try this pre-commit https://www.npmjs.org/package/pre-commit plugin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cam-technologies/time-booker/issues/43#issuecomment-48581897
> .

## 

Regards

Chris Laughlin

**Comment by madole** [comment]
Now that Martin has added the new pre-commit hook, can we close this?

**Comment by chrislaughlin** [comment]
Has the tho shall commit been removed ?

On Monday, July 21, 2014, Andrew McDowell notifications@github.com wrote:

> Now that Martin has added the new pre-commit hook, can we close this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cam-technologies/time-booker/issues/43#issuecomment-49676965
> .

## 

Sent from Gmail Mobile

**Comment by martinmicunda** [comment]
yes
